SET NOCOUNT ON;
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'General & Family Medicine' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-family-medicine.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Cardiology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-cardiology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Neurology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-neurology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Orthopedics & Bone Surgery' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-orthopedics.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Gastroenterology & Hepatology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-gastroenterology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Dermatology, Hair & Cosmetics' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-dermatology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Obstetrics, Gynecology & Fertility' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-gynecology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Pediatrics & Newborn Care' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-pediatrics.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Ophthalmology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-ophthalmology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Ear, Nose & Throat (ENT)' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-ent.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Urology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-urology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Endocrinology, Diabetes & Metabolism' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-endocrinology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Psychiatry' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-psychiatry.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Psychology & Counseling' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-psychology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Allergy & Immunology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-allergy-immunology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Hematology & Oncology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-hematology-oncology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Infectious Diseases' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-infectious-diseases.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Pulmonology (Lung & Respiratory)' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-pulmonology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Rheumatology (Joints)' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-rheumatology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'General Surgery' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-general-surgery.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Neurosurgery' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-neurosurgery.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Plastic & Reconstructive Surgery' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-plastic-surgery.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Anesthesiology' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-anesthesiology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Radiology & Imaging' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-radiology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Pathology & Laboratory' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-pathology.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Emergency Medicine' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-emergency-medicine.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Physical Medicine & Rehabilitation' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-pmr.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Dentistry' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-dentistry.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Sports Medicine' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-sports-medicine.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Geriatric Medicine' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-geriatrics.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Nutrition & Dietetics' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-nutrition.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Sleep Medicine' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-sleep-medicine.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Acupuncture' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-acupuncture.png';
UPDATE [adviceCategories] SET [AdviceCategoryname] = N'Catgut Embedding & Weight Management' WHERE [AdviceCategoryPicturePath] = N'/uploads/advices/specialty-catgut-embedding.png';
